# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='leave',
            table=None,
        ),
    ]
